#!/bin/bash -x
source /etc/environment
ehome="$ENLIGHTED_HOME"

cd $ehome/apache2/installation/

sudo chmod 755 -R $EM_MGMT_BASE/em_mgmt/

sudo mkdir -p $ENL_APP_HOME/Enlighted/UpgradeImages
 
sudo chmod 775 $ENL_APP_HOME/Enlighted/UpgradeImages

sudo chown $TOMCAT_USER:$TOMCAT_USER $ENL_APP_HOME/Enlighted/UpgradeImages

#sudo rm -f /media/usb

#sudo cp $ENLIGHTED_HOME/usbmount.conf /etc/usbmount/
#sudo chown root:root  /etc/usbmount/usbmount.conf
#sudo chmod 644 /etc/usbmount/usbmount.conf

sudo chmod 751 $TOMCAT_LOG/

if [ ! -f "$ENL_APP_HOME/Enlighted/adminpasswd" ]
then
	adminpass=$(psql -U postgres -x ems -c "select password from users where email = 'admin' limit 1" | grep password | cut -d " " -f3)
	if test -z "$adminpass"
	then
		echo -n "admin" | md5sum | cut -d" " -f1 > $ENL_APP_HOME/Enlighted/adminpasswd
	else
		echo "$adminpass" > $ENL_APP_HOME/Enlighted/adminpasswd
	fi
	sudo chmod 775 $ENL_APP_HOME/Enlighted/adminpasswd
	sudo chown $TOMCAT_USER:$TOMCAT_USER $ENL_APP_HOME/Enlighted/adminpasswd
fi

sudo chmod 755 /bin/authadmin.sh

# Remove tomcat-manager and tomcat-host-manager
sudo rm -f $ENL_APP_HOME/conf/Catalina/localhost/manager.xml
sudo rm -f $ENL_APP_HOME/conf/Catalina/localhost/host-manager.xml

##Insert/update python variables in apache
function  updatepythonenv(){
	sudo sed -i "/$1/d" $2
	sudo sed -i "$ a os.environ.setdefault(\"$1\", \"$3\")" $2
}
updatepythonenv ENL_APP_HOME $EM_MGMT_HOME/enlenv.py  $ENL_APP_HOME
updatepythonenv ENL_TOMCAT_HOME $EM_MGMT_HOME/enlenv.py $ENL_TOMCAT_HOME
updatepythonenv OPT_ENLIGHTED $EM_MGMT_HOME/enlenv.py $OPT_ENLIGHTED 
updatepythonenv ENLIGHTED_HOME $EM_MGMT_HOME/enlenv.py $ENLIGHTED_HOME 
updatepythonenv EM_MGMT_BASE $EM_MGMT_HOME/enlenv.py $EM_MGMT_BASE
updatepythonenv ENL_APACHE_HOME $EM_MGMT_HOME/enlenv.py $ENL_APACHE_HOME 

startapache=$(sudo /etc/init.d/apache2 start)
		
        sudo touch $ENL_APP_HOME/Enlighted/emsmode
        sudo chown $TOMCAT_USER:$TOMCAT_USER $ENL_APP_HOME/Enlighted/emsmode
		sudo chmod 777 $ENL_APP_HOME/Enlighted/emsmode
        sudo echo NORMAL > $ENL_APP_HOME/Enlighted/emsmode
		
		sudo cp $ehome/checkandsetemmode.sh /bin/checkandsetemmode.sh
		sudo chown root:root /bin/checkandsetemmode.sh
		sudo chmod 755 /bin/checkandsetemmode.sh
		
		sudo service udev restart
		
		#sudo cp $ENLIGHTED_HOME/rc.local /etc/rc.local
		#sudo chown root:root /etc/rc.local
		#sudo chmod 755 /etc/rc.local
		
		sudo cp $ehome/dailybackup.sh $OPT_ENLIGHTED/DB/dailybackup.sh
		
		#chmod 0440 ./sudoers
		#sudo cp ./sudoers /etc/
		#sudo chown root:root /etc/sudoers
		
		cp ./server.xml $ENL_APP_HOME/conf/server.xml
		
		cp ./web.xml $ENL_APP_HOME/conf/web.xml
		
		# Add www-data to tomcat group
		sudo sed -i.bak  's/\('$TOMCAT_USER':x:[0-9]*:\).*/\1www-data/' /etc/group
		
		mkdir $ehome/django_cache
		
		sudo updatedb
		

#Future backups should not use the stale ec data which might be based on different schema.
rm -f $OPT_ENLIGHTED/DB/DBBK/daily_ec_dump.backup

if [ ! -f "$ENL_APP_HOME/Enlighted/emsmode" ]
then
	sudo cp $ehome/emsmode $ENL_APP_HOME/Enlighted/
	sudo chmod 777 $ENL_APP_HOME/Enlighted/emsmode
	sudo chown $TOMCAT_USER:$TOMCAT_USER $ENL_APP_HOME/Enlighted/emsmode
fi
