#!/bin/bash -x

chmod 755 /tmp/em_all/home/enlighted/setAllEMEnvironment.sh 
/tmp/em_all/home/enlighted/setAllEMEnvironment.sh

source /etc/environment
sudo mkdir -p $ENL_APP_HOME/Enlighted/bkRestoreFolderTemp
sudo chmod 775 $ENL_APP_HOME/Enlighted/bkRestoreFolderTemp
sudo chown $TOMCAT_USER:$TOMCAT_USER $ENL_APP_HOME/Enlighted/bkRestoreFolderTemp
cd /tmp/em_all
sudo cp etc/apt/sources.list /etc/apt/sources.list
sudo cp etc/bind/named.conf.options /etc/bind/named.conf.options


sudo service bind9 restart
##Remove ntp entries 
sudo service ntp stop
sudo update-rc.d -f ntp remove
