#!/bin/bash -x
# Run this before removing this package, it requires root privilage
source /etc/environment

if [ ! -z "$1" ]
then
	echo "***********************setting ENL_APP_HOME from passed argument to shell************"
	export ENL_APP_HOME="$1"
fi
if [ -z "$ENL_APP_HOME"  ]
then
	echo "***********************setting ENL_APP_HOME hardcoded to /var/lib/tomcat6 as it is not still set************"
        export ENL_APP_HOME="/var/lib/tomcat6"
fi


if [ ! -z "$2" ]
then
	echo "***********************setting ENLIGHTED_HOME from passed argument to shell************"
	export ENLIGHTED_HOME="$2"
fi
if [ -z "$ENLIGHTED_HOME"  ]
then
	echo "***********************setting ENLIGHTED_HOME hardcoded to /home/enlighted as it is not still set************"
        export ENLIGHTED_HOME="/home/enlighted"
fi

if [ ! -z "$3" ]
then
	echo "***********************setting EM_MGMT_BASE from passed argument to shell************"
	export EM_MGMT_BASE="$3"
fi
if [ -z "$EM_MGMT_BASE"  ]
then
	echo "***********************setting EM_MGMT_BASE hardcoded to /var/wwww as it is not still set************"
        export EM_MGMT_BASE="/var/www"
fi


if [ ! -z "$4" ]
then
	echo "***********************setting OPT_ENLIGHTED from passed argument to shell************"
	export OPT_ENLIGHTED="$4"
fi
if [ -z "$OPT_ENLIGHTED"  ]
then
	echo "***********************setting OPT_ENLIGHTED hardcoded to /opt/enLighted as it is not still set************"
        export OPT_ENLIGHTED="/opt/enLighted"
fi

if [ -d $OPT_ENLIGHTED/adr ]
then
        echo "$OPT_ENLIGHTED/ard Directory exists!!!!"
else
        echo "Creating $OPT_ENLIGHTED/adr directory"
        mkdir $OPT_ENLIGHTED/adr
fi
ADR_PATH=$OPT_ENLIGHTED/adr
DBUSER=postgres
DBHOST=localhost
DB=adr
ps -ef |grep postgresql |grep -v grep > /dev/null
if [ $? -eq 0 ]
        then
                if [ `psql -q -U ${DBUSER} -h ${DBHOST}  -t -c "select count(*) from pg_database where datname='${DB}'"` -eq 1 ]
                        then

                                mkdir -p ${ADR_PATH}/tempExtract
                                dumpfileprefix=adr_dump_preupgradebkp

                                #-- Take backup of existing war and database

                                echo "Taking backup of Existing application.."

                                sudo cp ${ADR_PATH}/adr.jar ${ADR_PATH}/tempExtract/adr_bkp.jar

                                echo "Taking backup of database.."
                                /usr/bin/pg_dump -U $DBUSER -h $DBHOST -b -f "${ADR_PATH}/tempExtract/${dumpfileprefix}.sql" $DB

				p1=`ps -eaf | grep adr.jar | grep -v grep | wc -l`
                       		if [ ${p1} -ne 0 ]
                       		then
                                	echo "Closing the existing adr.jar process!!!!"
                             		pid=`ps -eaf | grep adr.jar | grep -v grep | sed 's/ \+ /\ /g' | cut -d " " -f2`
                             		sudo kill -9 ${pid}
				fi
                                echo "Undeploying application.."
                                sudo rm -fr ${ADR_PATH}/adr.jar

                        else
                                 echo "First time install"

                fi
        else
                echo "Postgres not running. Maybe first time install"
fi

