#!/bin/bash -x
# Run this before removing this package, it requires root privilage


sudo bash /opt/enLighted/communicator/setcron_communicator.sh
chmod +x /opt/enLighted/communicator/scripts/ems_communicator.sh 