#!/bin/bash -x
# Run this before removing this package, it requires root privilage

#sudo chown root:root /etc/default/rcS
#sudo chmod 644 /etc/default/rcS

sudo grep -v exit /etc/rc.local > rc.local.temp
echo /usr/local/google/home/enlighted/scripts/avahiremoval.sh >> rc.local.temp
echo exit 0 >> rc.local.temp
sudo mv rc.local.temp /etc/rc.local
sudo chown root:root /etc/rc.local
sudo chmod 755 /etc/rc.local
