#!/bin/bash -x
# Run this before removing this package, it requires root privilage
source /etc/environment
TOMCAT_PATH=$ENL_APP_HOME

echo "*** Undeploying EM application.. ***"
sudo rm -f ${TOMCAT_PATH}/webapps/ems.war
sudo rm -fr ${TOMCAT_PATH}/webapps/ems/
sudo rm -fr ${TOMCAT_PATH}/work/Catalina/localhost/ems

sudo rm -f ${TOMCAT_PATH}/webapps/ems_mgmt.war
sudo rm -fr ${TOMCAT_PATH}/webapps/ems_mgmt/
sudo rm -fr ${TOMCAT_PATH}/work/Catalina/localhost/ems_mgmt/
