#!/bin/bash -x
# Run this before removing this package, it requires root privilage

# Install SNAP Monitoring tool
# if [ -x /etc/init.d/enLightedZigbeeGW ]; then
# 	/usr/sbin/update-rc.d enLightedZigbeeGW start 98 2 3 4 5 . stop 20 0 1 6 .
# fi


if [ ! -f "/var/lib/tomcat6/Enlighted/cloudServerInfo.xml" ]
then
    cp /home/enlighted/cloudServerInfo.xml /var/lib/tomcat6/Enlighted/cloudServerInfo.xml
fi

if [ ! -f "$ENL_APP_HOME/Enlighted/kafka-proxy.properties" ]
then 
    mv $ENLIGHTED_HOME/kafka-proxy.properties $ENL_APP_HOME/Enlighted/kafka-proxy.properties
fi

chmod +x /home/enlighted/*.sh

#change permission on authorized keys
chmod 755 /home/enlighted/.ssh
chmod 644 /home/enlighted/.ssh/authorized_keys

# Copy Tomcat tomcat-users.xml to /etc/tomcat6/tomcat-users.xml
cp /home/enlighted/tomcat-users.xml /etc/tomcat6/tomcat-users.xml
# Copy Tomcat context.xml to /etc/tomcat6/context.xml
cp /home/enlighted/context.xml /etc/tomcat6/context.xml
# 1000 is user id for enlighted user
chown -R 1000:1000 /home/enlighted
chown -R 1000:1000 /opt/enLighted
chmod -R 777 /opt/enLighted/DB/
chown -R tomcat6:tomcat6 /var/lib/tomcat6/Enlighted
chmod 775 -R /var/lib/tomcat6/Enlighted
chown -R tomcat6:tomcat6 /var/lib/tomcat6/webapps

if [ -f "/etc/logrotate.d/tomcat6" ]
then
  sudo rm  -f /etc/logrotate.d/tomcat6
fi

if [ ! -f "/var/lib/tomcat6/webapps/ROOT/heartbeat.jsp" ]
then
    cp /home/enlighted/heartbeat.jsp /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp
    chown tomcat6:tomcat6 /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp
else
    
    if [[ ! $(grep systat /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp) =~ "systat" ]]
    then
        cp /home/enlighted/heartbeat.jsp /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp
    	chown tomcat6:tomcat6 /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp
    fi
fi

if [[ ! $(grep maintenance /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp) =~ "maintenance" ]]
then
    sed -i 's/\(<div\ id="systat">\)/\1<span\ id="maintenance">N<\/span>/' /var/lib/tomcat6/webapps/ROOT/heartbeat.jsp
fi

chmod -R 775 /var/lib/tomcat6/webapps/ROOT

ps -ef |grep postgresql |grep -v grep > /dev/null

if [ $? -eq 0 ]
then
   if [ `psql -q -U postgres -h localhost -p 5433 -t -c "select count(*) from pg_database where datname='ems'"` -eq 1 ]
   then
	echo "old clause to remove firstboot files..."
		#remove the firstboot files
    else 
      	echo "*** ems DB not exists ***"
	chmod +x /home/enlighted/01InstallDB.sh
	/home/enlighted/01InstallDB.sh
    fi
else
    echo "*** postgres not running ***"
fi


sudo chmod 755 /opt/enLighted/adr/adrsetcron.sh

sudo bash /home/enlighted/setcron.sh

sudo service cron restart

sudo rm -f /usr/sbin/bacnetd
sudo rm -rf /var/lib/tomcat6/Enlighted/bacnet*
sudo rm -rf /opt/enLighted/DB/restoreDB.sh
