#!/bin/bash -x
# Run this before removing this package, it requires root privilage
source /etc/environment
sudo bash $OPT_ENLIGHTED/communicator/communicatorsetcron.sh
sudo service cron restart

sudo mkdir $OPT_ENLIGHTED/communicator/syncdata/
sudo chmod 777 $OPT_ENLIGHTED/communicator/syncdata/

sudo chmod 600 $OPT_ENLIGHTED/communicator/enlightedTunnelKey
