#!/bin/bash -x


cd /home/enlighted/upgrade/

cp log4j.properties /var/lib/tomcat6/Enlighted/ems_log4j/log4j.properties
chown tomcat6:tomcat6 /var/lib/tomcat6/Enlighted/ems_log4j/log4j.properties

if [ ! -d "/var/lib/tomcat6/Enlighted/dataPullRequests" ]
then
	mkdir -p /var/lib/tomcat6/Enlighted/dataPullRequests
	chown -R tomcat6:tomcat6 /var/lib/tomcat6/Enlighted/dataPullRequests
fi

cp replica_check.sh /home/enlighted
chown enlighted:enlighted /home/enlighted/replica_check.sh
chmod 744 /home/enlighted/replica_check.sh

cp replica_daily_backups.sh /home/enlighted
chown enlighted:enlighted /home/enlighted/replica_daily_backups.sh
chmod 744 /home/enlighted/replica_daily_backups.sh
chown -R tomcat6:tomcat6 /var/lib/tomcat6/Enlighted/logs/


sudo rm -rf /var/lib/tomcat6/webapps/em_cloud_instance*
sudo rm -rf /var/lib/tomcat6/work/Catalina/localhost/em_cloud_instance/
sudo cp em_cloud_instance.war /var/lib/tomcat6/webapps/
sudo service tomcat6 restart
sudo service apache2 restart