#!/bin/bash -x
# Run this before removing this package, it requires root privilage

# Add AUTHBIND to tomcat6 script in /etc/default
grep -v "AUTHBIND" /etc/default/tomcat6 > /tmp/tomcat6
echo "AUTHBIND=yes" >> /tmp/tomcat6
cp /tmp/tomcat6 /etc/default/tomcat6

# Install SNAP Monitoring tool
# if [ -x /etc/init.d/enLightedZigbeeGW ]; then
# 	/usr/sbin/update-rc.d enLightedZigbeeGW start 98 2 3 4 5 . stop 20 0 1 6 .
# fi
chmod 0440 /home/enlighted/sudoers
sudo cp /home/enlighted/sudoers /etc/
sudo chown root:root /etc/sudoers
sudo cp /home/enlighted/tomcat6 /etc/init.d/
sudo chown root:root /etc/init.d/tomcat6
sudo chmod +x /etc/init.d/tomcat6
chmod +x /home/enlighted/*.sh

# Copy Tomcat server.xml to /etc/tomcat6/server.xml
cp /home/enlighted/server.xml /etc/tomcat6/server.xml
#change permission on authorized keys
chmod 755 /home/enlighted/.ssh
chmod 644 /home/enlighted/.ssh/authorized_keys

# Copy Tomcat tomcat-users.xml to /etc/tomcat6/tomcat-users.xml
cp /home/enlighted/tomcat-users.xml /etc/tomcat6/tomcat-users.xml
# Copy Tomcat web.xml to /etc/tomcat6/web.xml
cp /home/enlighted/web.xml /etc/tomcat6/web.xml
# Copy Tomcat context.xml to /etc/tomcat6/context.xml
cp /home/enlighted/context.xml /etc/tomcat6/context.xml
# 1000 is user id for enlighted user
chown 1000:1000 /home/enlighted/.pgpass
chown -R 1000:1000 /home/enlighted
chown -R 1000:1000 /opt/enLighted
chmod -R 777 /opt/enLighted/DB/
chown -R tomcat6:tomcat6 /var/lib/tomcat6/Enlighted
chown -R tomcat6:tomcat6 /var/lib/tomcat6/webapps

ps -ef |grep postgresql |grep -v grep > /dev/null
if [ $? -eq 0 ]
        then
               if [ `psql -q -U postgres -h localhost  -t -c "select count(*) from pg_database where datname='ems'"` -eq 1 ]

                        then

                                #--- Path of upgrade sql.. Assuming it'll have been copied by now..
                                UPGRADESQLPATH=/home/enlighted/upgradeSQL.sql

                                echo "Upgrading database..."
                                DBUSER=postgres
                                DBHOST=localhost
                                DB=ems


                                psql -U $DBUSER -h $DBHOST $DB < $UPGRADESQLPATH > /dev/null 2>&1
                                if [ $? -eq 0 ]
                                        then
                                                echo "Database upgrade completed successfully...Starting services.."
                                        else
                                                echo "Database was not upgraded succesfully.."
                                fi
                else 
                  	echo "ems DB not exists "
               		exit
                fi
        else
                echo "postgres not running"
fi

sudo bash /home/enlighted/setcron.sh