#!/bin/bash -x
# Run this before removing this package, it requires root privilage
source /etc/environment
if [ -d $OPT_ENLIGHTED/communicator ]
then
        echo "$OPT_ENLIGHTED/communicator Directory exists!!!!"
else
        echo "Creating $OPT_ENLIGHTED/communicator directory"
        mkdir $OPT_ENLIGHTED/communicator
fi
