SET statement_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;


alter table plugload_energy_consumption drop constraint plugload_energy_consumption_pkey;
alter table plugload_energy_consumption_hourly drop constraint plugload_energy_consumption_hourly_pkey;
alter table plugload_energy_consumption_daily drop constraint plugload_energy_consumption_daily_pkey;

alter table plugload_energy_consumption drop constraint plugload_energy_consumption_plugload_id_fkey;
alter table plugload_energy_consumption drop constraint plugload_energy_consumption_capture_at_plugload_id_key;

alter table plugload_energy_consumption_hourly drop constraint plugload_energy_consumption_hourly_plugload_id_fkey;
alter table plugload_energy_consumption_hourly drop constraint plugload_energy_consumption_hourly_capture_at_plugload_id_key;

alter table plugload_energy_consumption_daily drop constraint plugload_energy_consumption_daily_plugload_id_fkey;
alter table plugload_energy_consumption_daily drop constraint plugload_energy_consumption_daily_capture_at_plugload_id_key;