#!/bin/bash -x
# Run this before removing this package, it requires root privilage

TOMCAT_PATH=/var/lib/tomcat6

echo "*** Undeploying EM application.. ***"
sudo rm -f ${TOMCAT_PATH}/webapps/ems.war
sudo rm -fr ${TOMCAT_PATH}/webapps/ems/
sudo rm -fr ${TOMCAT_PATH}/work/Catalina/localhost/ems

sudo rm -f ${TOMCAT_PATH}/webapps/ems_mgmt.war
sudo rm -fr ${TOMCAT_PATH}/webapps/ems_mgmt/
sudo rm -fr ${TOMCAT_PATH}/work/Catalina/localhost/ems_mgmt/


if [ -d /opt/enLighted/adr ]
then
        echo "/opt/enLighted/ard Directory exists!!!!"
else
        echo "Creating /opt/enLighted/adr directory"
        mkdir /opt/enLighted/adr
fi