#!/bin/bash -x

sudo mkdir -p /var/lib/tomcat6/Enlighted/bkRestoreFolderTemp
sudo chmod 775 /var/lib/tomcat6/Enlighted/bkRestoreFolderTemp
sudo chown tomcat6:tomcat6 /var/lib/tomcat6/Enlighted/bkRestoreFolderTemp