#!/bin/bash -x
# Run this before removing this package, it requires root privilage
t1=$(sudo service tomcat6 status)
if [[ $t1 =~ "is running"  ]]
then
        echo "Tomcat6 is running......."
        sudo service tomcat6 stop
else
        echo "Tomcat6 not running ..........:"
fi


TOMCAT_PATH=/var/lib/tomcat6
mkdir -p ${TOMCAT_PATH}/Enlighted/tempExtract

echo "Taking backup of Existing application.."

sudo cp ${TOMCAT_PATH}/webapps/ems_mgmt.war ${TOMCAT_PATH}/Enlighted/tempExtract/ems_mgmt_bkp.war

echo "Undeploying application.."
sudo rm -f ${TOMCAT_PATH}/webapps/ems_mgmt.war
sudo rm -fr ${TOMCAT_PATH}/webapps/ems_mgmt
sudo rm -fr ${TOMCAT_PATH}/work/Catalina/localhost/ems_mgmt

